Traceback (most recent call last):
  File "/storage/emulated/0/dpl/lib/core/repl_syntax_highlighter.py", line 16, in <module>
    json_config = json.loads(open(os.path.join(info.BINDIR, "repl_conf/colors_n_stuff.json")).read())
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/json/decoder.py", line 361, in raw_decode
    obj, end = self.scan_once(s, idx)
               ~~~~~~~~~~~~~~^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 119 column 9 (char 3846)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/emulated/0/dpl/lib/core/repl_syntax_highlighter.py", line 18, in <module>
    json_config = json.loads(open(os.path.join("../../repl_conf/colors_n_stuff.json")).read())
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../repl_conf/colors_n_stuff.json'
